name: repick
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  # 기본 의존성
  - pip
  - uvicorn
  - pandas>=2.2.2

  - pip:
      # LangChain 생태계
      - langchain>=0.2.5
      - langchain-openai>=0.1
      - langchain-upstage>=0.1
      - langchain-chroma>=0.1
      - langgraph>=0.0

      # 벡터 DB & 검색
      - chromadb>=0.4.24

      # PDF & 문서 처리
      - pymupdf>=1.24.1
      - pypdf>=4.2.0
      - pdfplumber>=0.11.1
      - pdfminer-six>=20231228

      # API & 웹
      - fastapi
      - uvicorn
      - requests>=2.31.0

      # AI & ML 도구
      - huggingface-hub>=0.23

      # 유틸리티
      - python-dotenv>=1.0.1
      - pydantic>=2.7.4
      - tqdm
      - tenacity==8.3.0
      - tiktoken>=0.7
      - pillow>=10.3.0

      # MongoDB 관련
      - pymongo
